### ISSUE TITLE
Error:  No such file or directory (when ./scripts/build.sh -c analytical)

### ISSUE THREAD

**Issue by Honghe** [aliyun/SimAI#1]
Environment:
- Ubuntu 22.04

Setps:
```
# Clone the repository
$ git clone https://github.com/aliyun/SimAI.git
$ cd ./SimAI/

# Clone submodules
$ git submodule update --init --recursive

# Compile SimAI-Analytical
$ ./scripts/build.sh -c analytical
```

Error:
```
./build.sh: line 35: ./build.sh: No such file or directory
```

**Comment by Huoyuan100861** [comment]
Thanks for your attention and use of SimAI, we apologize for this unexpected issue and will fix it promptly. In the future official release, comprehensive testing will be conducted. Welcome to follow up continuously.
