### ISSUE TITLE
Is the paper name Tuning or Tunning. SimAI: Unifying Architecture Design and Performance Tunning for Large-Scale Large Language Model Training with Scalability and Precision

### ISSUE THREAD

**Issue by Bryan-pix** [aliyun/SimAI#23]
Is the NSDI 25' paper name **Tuning** or **Tunning**? I guess should be "Tuning".
SimAI: Unifying Architecture Design and Performance Tunning for Large-Scale Large Language Model Training with Scalability and Precision

**Comment by Huoyuan100861** [comment]
> Is the NSDI 25' paper name **Tuning** or **Tunning**? I guess should be "Tuning". SimAI: Unifying Architecture Design and Performance Tunning for Large-Scale Large Language Model Training with Scalability and Precision

You've got eagle eyes!

**Comment by Bryan-pix** [comment]
lol，good paper though

**Comment by Huoyuan100861** [comment]
Have fixed.
