### ISSUE TITLE
Seems SimCCL is not released yet?

### ISSUE THREAD

**Issue by CodingYuanLiu** [aliyun/SimAI#3]
Hello! There is only Licence in the SimCCL Repo. 

It seems that the whole project is not fully open source

By the way, could you tell us when the SimAI tutorials and other materials will be released？

Thanks！

**Comment by Huoyuan100861** [comment]
> Hello! There is only Licence in the SimCCL Repo.
> 
> It seems that the whole project is not fully open source
> 
> By the way, could you tell us when the SimAI tutorials and other materials will be released？
> 
> Thanks！

Thank you for your interest in SimAI. Currently, the main functionalities of SimCCL can be found in the astra-sim-alibabacloud repository with examples, so it should not affect end-to-end testing. The SimCCL repository is expected to be completed and uploaded next week.

**Comment by CodingYuanLiu** [comment]
I see. Thanks
