### ISSUE TITLE
customizing network topology

### ISSUE THREAD

**Issue by thunderZH963** [aliyun/SimAI#37]
I have seen how to configure the HPN network topology here(https://github.com/aliyun/SimAI/blob/master/astra-sim-alibabacloud/inputs/topo/gen_HPN_7.0_topo_mulgpus_one_link.py). 
What should I do if I want to customize a topology?
such as a topo consisting of 2 * 2 * 2 interconnected GPUs

**Comment by Huoyuan100861** [comment]
> I have seen how to configure the HPN network topology here(https://github.com/aliyun/SimAI/blob/master/astra-sim-alibabacloud/inputs/topo/gen_HPN_7.0_topo_mulgpus_one_link.py). What should I do if I want to customize a topology? such as a topo consisting of 2 * 2 * 2 interconnected GPUs

You can refer to https://github.com/aliyun/SimAI/blob/master/docs/Tutorial.md#-topo-setting to understand the meaning of each field in the network topology file. With a basic understanding, you can construct any desired topology.

**Comment by thunderZH963** [comment]
Okay. I get. Thanks.
