### ISSUE TITLE
SimAI full simulation how to gen scale_out traffic flows?

### ISSUE THREAD

**Issue by huangxm0618** [aliyun/SimAI#39]
if need to gen scale_out traffic ,how to config and gen workload ?  
please give an example , as gpt-7B megtron ....

**Comment by Huoyuan100861** [comment]
> if need to gen scale_out traffic ,how to config and gen workload ? please give an example , as gpt-7B megtron ....

In the example, the workload demonstrates scale-out traffic. Normally, any multi-nodes training scenario would involve scale-out traffic, be it TP, EP, or DP, and so on.

**Comment by huangxm0618** [comment]
but, I use 7B,22B,175B workload to simulation, only see the traffic in nodes（scale_up），can not see the scale-out traffic

**Comment by Huoyuan100861** [comment]
> but, I use 7B,22B,175B workload to simulation, only see the traffic in nodes（scale_up），can not see the scale-out traffic

How did you arrive at the conclusion that "can not see the scale-out traffic"? The third column in the first row of the workload, 'grad_gather/grad_param_comm', represents the DP communication, which is generally inter-machine communication.

**Comment by huangxm0618** [comment]
i see in getflowmodels src/dest ，the Difference between src and  dst No more than 8 。 Whether this view is wrong？

**Comment by huangxm0618** [comment]
grad_gather can see scale_out traffic
