### ISSUE TITLE
Hardware configuration

### ISSUE THREAD

**Issue by HastyMonkey** [aliyun/SimAI#46]
If I need to redevelop this code, are there any requirements for the hardware configuration?

**Comment by Huoyuan100861** [comment]
> If I need to redevelop this code, are there any requirements for the hardware configuration?

Developing with SimAI doesn't require high-end specifications, an 8-core CPU with 16GB RAM should be sufficient. Of course, better configurations would be ideal (within a certain range, higher specs translate to faster NS-3 performance).
