### ISSUE TITLE
Question about understanding microAllReduce.txt file format

### ISSUE THREAD

**Issue by beatlesforever** [aliyun/SimAI#58]
I am trying to understand the structure and meaning of each parameter in the `microAllReduce.txt ` file. Below is an example of the file contents:

```
HYBRID_TRANSFORMER_FWD_IN_BCKWD model_parallel_NPU_group: 8 ep: 1 pp: 1 vpp: 8 ga: 1 all_gpus: 8 checkpoints: 0 checkpoint_initiates: 0
2
embedding_layer     -1 556000  ALLREDUCE   16777216      1       NONE 0        1      NONE   0      1
embedding_layer     -1 556000  ALLREDUCE   67108864      1       NONE 0        1      NONE   0      1
```

I would like to know:

1. What does each parameter in the header represent (e.g., model_parallel_NPU_group, ep, pp, etc.)? What are their units?
2. For the rows:

- What does each column mean?

- Are -1, 556000, ALLREDUCE, 16777216, etc., tied to specific units or operations?

A brief explanation of the file structure would be appreciated. Thank you!

**Comment by Huoyuan100861** [comment]
> 我正在尝试了解文件中每个参数的结构和含义`microAllReduce.txt `。以下是文件内容的示例：
> 
> ```
> HYBRID_TRANSFORMER_FWD_IN_BCKWD model_parallel_NPU_group: 8 ep: 1 pp: 1 vpp: 8 ga: 1 all_gpus: 8 checkpoints: 0 checkpoint_initiates: 0
> 2
> embedding_layer     -1 556000  ALLREDUCE   16777216      1       NONE 0        1      NONE   0      1
> embedding_layer     -1 556000  ALLREDUCE   67108864      1       NONE 0        1      NONE   0      1
> ```
> 
> 我想知道：
> 
> 1. 标头中的各个参数代表什么（例如 model_parallel_NPU_group、ep、pp 等）？它们的单位是什么？
> 2. 对于行：
> 
> * 每列代表什么意思？
> * -1、556000、ALLREDUCE、16777216 等是否与特定单位或操作相关？
> 
> 希望能对文件结构进行简要说明。谢谢！

You can start by reading the content at https://github.com/aliyun/aicb/blob/master/training/tutorial.md. If you have any questions after that, please don't hesitate to submit them. We welcome your inquiries.

**Comment by beatlesforever** [comment]
Thank you for your response! I’ve reviewed the [tutorial.md](https://github.com/aliyun/aicb/blob/master/training/tutorial.md) you mentioned. However, I still have some specific questions about the file content:

1. **Is `16777216` measured in bytes (B)?** It looks like it might represent data size, possibly related to message size during communication, but I’m not sure about the exact unit.
2. **Is `1` measured in cycles?** It seems to describe some operation or time unit, but it’s not explicitly clarified in the documentation.

Thank you so much for your help! Looking forward to your clarification. 🙏

**Comment by Huoyuan100861** [comment]
> Thank you for your response! I’ve reviewed the [tutorial.md](https://github.com/aliyun/aicb/blob/master/training/tutorial.md) you mentioned. However, I still have some specific questions about the file content:
> 
> 1. **Is `16777216` measured in bytes (B)?** It looks like it might represent data size, possibly related to message size during communication, but I’m not sure about the exact unit.
> 2. **Is `1` measured in cycles?** It seems to describe some operation or time unit, but it’s not explicitly clarified in the documentation.
> 
> Thank you so much for your help! Looking forward to your clarification. 🙏

1. Yes;
2. Compute time, us.

**Comment by beatlesforever** [comment]
Thank you so much for your detailed explanation! 🙏
